version: "3.8"
services:
  backend:
    build: . # Build image from local Dockerfile
    environment:
      DB_HOST: db
      DB_PORT:     "${DB_PORT}"
      DB_USER:     "${DB_USER}"
      DB_PASSWORD: "${DB_PASS}"
      DB_NAME:     "${DB_NAME}"
    ports:
      - "3000:3000" # Expose port 3000 on host
    depends_on:
      - db # Wait until database service is loaded
    networks:
      - app-network
  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER:     "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
    networks:
      - app-network
networks: # Specify the network for bridging
  app-network:
    driver: bridge